services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - /storage:/data
    restart: unless-stopped
    networks:
      - app_net
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_net

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - minio
      - redis
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      #MINIO_BUCKET: music-bucket
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped
    networks:
      - app_net

volumes:
  minio_data:
networks:
  app_net: