services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # Porta para o console de administração
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - /storage:/data
      - /storage/.minio:/root/.minio
    restart: unless-stopped
    networks:
      - app_net

  app:
    build: .
    container_name: node_app
    expose:
      - "3000"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: music-bucket
    restart: unless-stopped
    networks:
      - app_net

volumes:
  minio_data:
networks:
  app_net: