services:
  sftpgo:
    build: ./sftpgo
    container_name: sftpgo
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:8080:8080"  # 🔥 só local (importante)
      - "2022:2022"
    environment:
      - SFTPGO_DATA_PROVIDER__DRIVER=postgresql
      - SFTPGO_DATA_PROVIDER__HOST=db
      - SFTPGO_DATA_PROVIDER__PORT=5432
      - SFTPGO_DATA_PROVIDER__USERNAME=${POSTGRES_USER}
      - SFTPGO_DATA_PROVIDER__PASSWORD=${POSTGRES_PASSWORD}
      - SFTPGO_DATA_PROVIDER__NAME=${POSTGRES_DB}
      - SFTPGO_COMMON__DEFENDER_ENABLED=true
      - SFTPGO_COMMON__IDLE_TIMEOUT=15
    volumes:
      - ./data:/data
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge